CREATE TABLE address (
       id SERIAL PRIMARY KEY,
       city VARCHAR(50) NOT NULL,
       address VARCHAR(255) NOT NULL,
       user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
       created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
       updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);